### ISSUE TITLE
解决多层异步嵌套带来的线程阻塞问题（目前spring-async依然存在此问题）

### ISSUE THREAD

**Issue by kaitezhan** [pengpan/fact-async#6]
1.这个是指比如我有10个异步任务，可能有1个还在执行，他9个已经处理完成,然后我在下面get的时候，刚好get的是还在执行的任务，导致阻塞是吗？
2.现在没维护了吗？

**Comment by awoter** [comment]
不是，嵌套阻塞是指线程池只有3个线程，而调拨A方法里一共涉及4个异步执行方法 比如：A->B->C->D  这种情况spring-async是会一直block的，而该框架是会异转同来解决block问题

**Comment by awoter** [comment]
> 1.这个是指比如我有10个异步任务，可能有1个还在执行，他9个已经处理完成,然后我在下面get的时候，刚好get的是还在执行的任务，导致阻塞是吗？
> 2.现在没维护了吗？

1、不是，嵌套阻塞是指线程池只有3个线程，而调拨A方法里一共涉及4个异步执行方法 比如：A->B->C->D 这种情况spring-async是会一直block的，而该框架是会异转同来解决block问题；
2、如果没bug相关问题就打算更新了，目前该框架处理稳定阶段；
